# Generated by Django 3.0.3 on 2020-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0004_payment_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_bid_rate',
            name='project',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
