# Generated by Django 3.2.2 on 2021-05-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_delete_payment_report'),
        ('hirer', '0007_auto_20210419_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_bid_rate',
            name='end_time',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin1.add_project'),
        ),
    ]
