# Generated by Django 3.2.2 on 2021-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0008_project_bid_rate_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_bid_rate',
            name='end_time',
        ),
        migrations.AddField(
            model_name='project_bid_rate',
            name='end_date',
            field=models.DateField(default='2021-05-01'),
        ),
    ]
