# Generated by Django 3.2.2 on 2021-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirer', '0009_auto_20210513_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_bid_rate',
            name='end_date',
            field=models.DateField(),
        ),
    ]
