# Generated by Django 3.0.3 on 2020-04-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_report',
        ),
    ]
